// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package policyengine

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockEngineBaggage creates a new instance of MockEngineBaggage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEngineBaggage(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEngineBaggage {
	mock := &MockEngineBaggage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockEngineBaggage is an autogenerated mock type for the EngineBaggage type
type MockEngineBaggage struct {
	mock.Mock
}

type MockEngineBaggage_Expecter struct {
	mock *mock.Mock
}

func (_m *MockEngineBaggage) EXPECT() *MockEngineBaggage_Expecter {
	return &MockEngineBaggage_Expecter{mock: &_m.Mock}
}

// GetLogFields provides a mock function for the type MockEngineBaggage
func (_mock *MockEngineBaggage) GetLogFields() map[string]any {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetLogFields")
	}

	var r0 map[string]any
	if returnFunc, ok := ret.Get(0).(func() map[string]any); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]any)
		}
	}
	return r0
}

// MockEngineBaggage_GetLogFields_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLogFields'
type MockEngineBaggage_GetLogFields_Call struct {
	*mock.Call
}

// GetLogFields is a helper method to define mock.On call
func (_e *MockEngineBaggage_Expecter) GetLogFields() *MockEngineBaggage_GetLogFields_Call {
	return &MockEngineBaggage_GetLogFields_Call{Call: _e.mock.On("GetLogFields")}
}

func (_c *MockEngineBaggage_GetLogFields_Call) Run(run func()) *MockEngineBaggage_GetLogFields_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockEngineBaggage_GetLogFields_Call) Return(stringToV map[string]any) *MockEngineBaggage_GetLogFields_Call {
	_c.Call.Return(stringToV)
	return _c
}

func (_c *MockEngineBaggage_GetLogFields_Call) RunAndReturn(run func() map[string]any) *MockEngineBaggage_GetLogFields_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockStepOutput creates a new instance of MockStepOutput. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStepOutput(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStepOutput {
	mock := &MockStepOutput{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockStepOutput is an autogenerated mock type for the StepOutput type
type MockStepOutput struct {
	mock.Mock
}

type MockStepOutput_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStepOutput) EXPECT() *MockStepOutput_Expecter {
	return &MockStepOutput_Expecter{mock: &_m.Mock}
}

// IsTerminal provides a mock function for the type MockStepOutput
func (_mock *MockStepOutput) IsTerminal() bool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for IsTerminal")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockStepOutput_IsTerminal_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsTerminal'
type MockStepOutput_IsTerminal_Call struct {
	*mock.Call
}

// IsTerminal is a helper method to define mock.On call
func (_e *MockStepOutput_Expecter) IsTerminal() *MockStepOutput_IsTerminal_Call {
	return &MockStepOutput_IsTerminal_Call{Call: _e.mock.On("IsTerminal")}
}

func (_c *MockStepOutput_IsTerminal_Call) Run(run func()) *MockStepOutput_IsTerminal_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockStepOutput_IsTerminal_Call) Return(b bool) *MockStepOutput_IsTerminal_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockStepOutput_IsTerminal_Call) RunAndReturn(run func() bool) *MockStepOutput_IsTerminal_Call {
	_c.Call.Return(run)
	return _c
}

// String provides a mock function for the type MockStepOutput
func (_mock *MockStepOutput) String() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for String")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockStepOutput_String_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'String'
type MockStepOutput_String_Call struct {
	*mock.Call
}

// String is a helper method to define mock.On call
func (_e *MockStepOutput_Expecter) String() *MockStepOutput_String_Call {
	return &MockStepOutput_String_Call{Call: _e.mock.On("String")}
}

func (_c *MockStepOutput_String_Call) Run(run func()) *MockStepOutput_String_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockStepOutput_String_Call) Return(s string) *MockStepOutput_String_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockStepOutput_String_Call) RunAndReturn(run func() string) *MockStepOutput_String_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockStep creates a new instance of MockStep. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStep[B EngineBaggage, O StepOutput](t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStep[B, O] {
	mock := &MockStep[B, O]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockStep is an autogenerated mock type for the Step type
type MockStep[B EngineBaggage, O StepOutput] struct {
	mock.Mock
}

type MockStep_Expecter[B EngineBaggage, O StepOutput] struct {
	mock *mock.Mock
}

func (_m *MockStep[B, O]) EXPECT() *MockStep_Expecter[B, O] {
	return &MockStep_Expecter[B, O]{mock: &_m.Mock}
}

// ApplyPolicy provides a mock function for the type MockStep
func (_mock *MockStep[B, O]) ApplyPolicy(baggage B) O {
	ret := _mock.Called(baggage)

	if len(ret) == 0 {
		panic("no return value specified for ApplyPolicy")
	}

	var r0 O
	if returnFunc, ok := ret.Get(0).(func(B) O); ok {
		r0 = returnFunc(baggage)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(O)
		}
	}
	return r0
}

// MockStep_ApplyPolicy_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ApplyPolicy'
type MockStep_ApplyPolicy_Call[B EngineBaggage, O StepOutput] struct {
	*mock.Call
}

// ApplyPolicy is a helper method to define mock.On call
//   - baggage
func (_e *MockStep_Expecter[B, O]) ApplyPolicy(baggage interface{}) *MockStep_ApplyPolicy_Call[B, O] {
	return &MockStep_ApplyPolicy_Call[B, O]{Call: _e.mock.On("ApplyPolicy", baggage)}
}

func (_c *MockStep_ApplyPolicy_Call[B, O]) Run(run func(baggage B)) *MockStep_ApplyPolicy_Call[B, O] {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(B))
	})
	return _c
}

func (_c *MockStep_ApplyPolicy_Call[B, O]) Return(v O) *MockStep_ApplyPolicy_Call[B, O] {
	_c.Call.Return(v)
	return _c
}

func (_c *MockStep_ApplyPolicy_Call[B, O]) RunAndReturn(run func(baggage B) O) *MockStep_ApplyPolicy_Call[B, O] {
	_c.Call.Return(run)
	return _c
}

// GetName provides a mock function for the type MockStep
func (_mock *MockStep[B, O]) GetName() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetName")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockStep_GetName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetName'
type MockStep_GetName_Call[B EngineBaggage, O StepOutput] struct {
	*mock.Call
}

// GetName is a helper method to define mock.On call
func (_e *MockStep_Expecter[B, O]) GetName() *MockStep_GetName_Call[B, O] {
	return &MockStep_GetName_Call[B, O]{Call: _e.mock.On("GetName")}
}

func (_c *MockStep_GetName_Call[B, O]) Run(run func()) *MockStep_GetName_Call[B, O] {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockStep_GetName_Call[B, O]) Return(s string) *MockStep_GetName_Call[B, O] {
	_c.Call.Return(s)
	return _c
}

func (_c *MockStep_GetName_Call[B, O]) RunAndReturn(run func() string) *MockStep_GetName_Call[B, O] {
	_c.Call.Return(run)
	return _c
}

// IsEligible provides a mock function for the type MockStep
func (_mock *MockStep[B, O]) IsEligible(baggage B) (bool, string) {
	ret := _mock.Called(baggage)

	if len(ret) == 0 {
		panic("no return value specified for IsEligible")
	}

	var r0 bool
	var r1 string
	if returnFunc, ok := ret.Get(0).(func(B) (bool, string)); ok {
		return returnFunc(baggage)
	}
	if returnFunc, ok := ret.Get(0).(func(B) bool); ok {
		r0 = returnFunc(baggage)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(B) string); ok {
		r1 = returnFunc(baggage)
	} else {
		r1 = ret.Get(1).(string)
	}
	return r0, r1
}

// MockStep_IsEligible_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsEligible'
type MockStep_IsEligible_Call[B EngineBaggage, O StepOutput] struct {
	*mock.Call
}

// IsEligible is a helper method to define mock.On call
//   - baggage
func (_e *MockStep_Expecter[B, O]) IsEligible(baggage interface{}) *MockStep_IsEligible_Call[B, O] {
	return &MockStep_IsEligible_Call[B, O]{Call: _e.mock.On("IsEligible", baggage)}
}

func (_c *MockStep_IsEligible_Call[B, O]) Run(run func(baggage B)) *MockStep_IsEligible_Call[B, O] {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(B))
	})
	return _c
}

func (_c *MockStep_IsEligible_Call[B, O]) Return(eligible bool, reason string) *MockStep_IsEligible_Call[B, O] {
	_c.Call.Return(eligible, reason)
	return _c
}

func (_c *MockStep_IsEligible_Call[B, O]) RunAndReturn(run func(baggage B) (bool, string)) *MockStep_IsEligible_Call[B, O] {
	_c.Call.Return(run)
	return _c
}

// PrepareDependencies provides a mock function for the type MockStep
func (_mock *MockStep[B, O]) PrepareDependencies(ctx context.Context, baggage *B) error {
	ret := _mock.Called(ctx, baggage)

	if len(ret) == 0 {
		panic("no return value specified for PrepareDependencies")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *B) error); ok {
		r0 = returnFunc(ctx, baggage)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStep_PrepareDependencies_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PrepareDependencies'
type MockStep_PrepareDependencies_Call[B EngineBaggage, O StepOutput] struct {
	*mock.Call
}

// PrepareDependencies is a helper method to define mock.On call
//   - ctx
//   - baggage
func (_e *MockStep_Expecter[B, O]) PrepareDependencies(ctx interface{}, baggage interface{}) *MockStep_PrepareDependencies_Call[B, O] {
	return &MockStep_PrepareDependencies_Call[B, O]{Call: _e.mock.On("PrepareDependencies", ctx, baggage)}
}

func (_c *MockStep_PrepareDependencies_Call[B, O]) Run(run func(ctx context.Context, baggage *B)) *MockStep_PrepareDependencies_Call[B, O] {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*B))
	})
	return _c
}

func (_c *MockStep_PrepareDependencies_Call[B, O]) Return(err error) *MockStep_PrepareDependencies_Call[B, O] {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStep_PrepareDependencies_Call[B, O]) RunAndReturn(run func(ctx context.Context, baggage *B) error) *MockStep_PrepareDependencies_Call[B, O] {
	_c.Call.Return(run)
	return _c
}

// NewMockEngine creates a new instance of MockEngine. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEngine[Baggage EngineBaggage, Output StepOutput](t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEngine[Baggage, Output] {
	mock := &MockEngine[Baggage, Output]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockEngine is an autogenerated mock type for the Engine type
type MockEngine[Baggage EngineBaggage, Output StepOutput] struct {
	mock.Mock
}

type MockEngine_Expecter[Baggage EngineBaggage, Output StepOutput] struct {
	mock *mock.Mock
}

func (_m *MockEngine[Baggage, Output]) EXPECT() *MockEngine_Expecter[Baggage, Output] {
	return &MockEngine_Expecter[Baggage, Output]{mock: &_m.Mock}
}

// IsBreakerTripped provides a mock function for the type MockEngine
func (_mock *MockEngine[Baggage, Output]) IsBreakerTripped(baggage Baggage) (bool, error) {
	ret := _mock.Called(baggage)

	if len(ret) == 0 {
		panic("no return value specified for IsBreakerTripped")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(Baggage) (bool, error)); ok {
		return returnFunc(baggage)
	}
	if returnFunc, ok := ret.Get(0).(func(Baggage) bool); ok {
		r0 = returnFunc(baggage)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(Baggage) error); ok {
		r1 = returnFunc(baggage)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockEngine_IsBreakerTripped_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsBreakerTripped'
type MockEngine_IsBreakerTripped_Call[Baggage EngineBaggage, Output StepOutput] struct {
	*mock.Call
}

// IsBreakerTripped is a helper method to define mock.On call
//   - baggage
func (_e *MockEngine_Expecter[Baggage, Output]) IsBreakerTripped(baggage interface{}) *MockEngine_IsBreakerTripped_Call[Baggage, Output] {
	return &MockEngine_IsBreakerTripped_Call[Baggage, Output]{Call: _e.mock.On("IsBreakerTripped", baggage)}
}

func (_c *MockEngine_IsBreakerTripped_Call[Baggage, Output]) Run(run func(baggage Baggage)) *MockEngine_IsBreakerTripped_Call[Baggage, Output] {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(Baggage))
	})
	return _c
}

func (_c *MockEngine_IsBreakerTripped_Call[Baggage, Output]) Return(tripped bool, reason error) *MockEngine_IsBreakerTripped_Call[Baggage, Output] {
	_c.Call.Return(tripped, reason)
	return _c
}

func (_c *MockEngine_IsBreakerTripped_Call[Baggage, Output]) RunAndReturn(run func(baggage Baggage) (bool, error)) *MockEngine_IsBreakerTripped_Call[Baggage, Output] {
	_c.Call.Return(run)
	return _c
}

// Run provides a mock function for the type MockEngine
func (_mock *MockEngine[Baggage, Output]) Run(ctx context.Context, baggage *Baggage) (EngineOutput[Baggage, Output], error) {
	ret := _mock.Called(ctx, baggage)

	if len(ret) == 0 {
		panic("no return value specified for Run")
	}

	var r0 EngineOutput[Baggage, Output]
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *Baggage) (EngineOutput[Baggage, Output], error)); ok {
		return returnFunc(ctx, baggage)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *Baggage) EngineOutput[Baggage, Output]); ok {
		r0 = returnFunc(ctx, baggage)
	} else {
		r0 = ret.Get(0).(EngineOutput[Baggage, Output])
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *Baggage) error); ok {
		r1 = returnFunc(ctx, baggage)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockEngine_Run_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Run'
type MockEngine_Run_Call[Baggage EngineBaggage, Output StepOutput] struct {
	*mock.Call
}

// Run is a helper method to define mock.On call
//   - ctx
//   - baggage
func (_e *MockEngine_Expecter[Baggage, Output]) Run(ctx interface{}, baggage interface{}) *MockEngine_Run_Call[Baggage, Output] {
	return &MockEngine_Run_Call[Baggage, Output]{Call: _e.mock.On("Run", ctx, baggage)}
}

func (_c *MockEngine_Run_Call[Baggage, Output]) Run(run func(ctx context.Context, baggage *Baggage)) *MockEngine_Run_Call[Baggage, Output] {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*Baggage))
	})
	return _c
}

func (_c *MockEngine_Run_Call[Baggage, Output]) Return(output EngineOutput[Baggage, Output], err error) *MockEngine_Run_Call[Baggage, Output] {
	_c.Call.Return(output, err)
	return _c
}

func (_c *MockEngine_Run_Call[Baggage, Output]) RunAndReturn(run func(ctx context.Context, baggage *Baggage) (EngineOutput[Baggage, Output], error)) *MockEngine_Run_Call[Baggage, Output] {
	_c.Call.Return(run)
	return _c
}

// RunBypassBreaker provides a mock function for the type MockEngine
func (_mock *MockEngine[Baggage, Output]) RunBypassBreaker(ctx context.Context, baggage *Baggage) (EngineOutput[Baggage, Output], error) {
	ret := _mock.Called(ctx, baggage)

	if len(ret) == 0 {
		panic("no return value specified for RunBypassBreaker")
	}

	var r0 EngineOutput[Baggage, Output]
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *Baggage) (EngineOutput[Baggage, Output], error)); ok {
		return returnFunc(ctx, baggage)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *Baggage) EngineOutput[Baggage, Output]); ok {
		r0 = returnFunc(ctx, baggage)
	} else {
		r0 = ret.Get(0).(EngineOutput[Baggage, Output])
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *Baggage) error); ok {
		r1 = returnFunc(ctx, baggage)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockEngine_RunBypassBreaker_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RunBypassBreaker'
type MockEngine_RunBypassBreaker_Call[Baggage EngineBaggage, Output StepOutput] struct {
	*mock.Call
}

// RunBypassBreaker is a helper method to define mock.On call
//   - ctx
//   - baggage
func (_e *MockEngine_Expecter[Baggage, Output]) RunBypassBreaker(ctx interface{}, baggage interface{}) *MockEngine_RunBypassBreaker_Call[Baggage, Output] {
	return &MockEngine_RunBypassBreaker_Call[Baggage, Output]{Call: _e.mock.On("RunBypassBreaker", ctx, baggage)}
}

func (_c *MockEngine_RunBypassBreaker_Call[Baggage, Output]) Run(run func(ctx context.Context, baggage *Baggage)) *MockEngine_RunBypassBreaker_Call[Baggage, Output] {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*Baggage))
	})
	return _c
}

func (_c *MockEngine_RunBypassBreaker_Call[Baggage, Output]) Return(output EngineOutput[Baggage, Output], err error) *MockEngine_RunBypassBreaker_Call[Baggage, Output] {
	_c.Call.Return(output, err)
	return _c
}

func (_c *MockEngine_RunBypassBreaker_Call[Baggage, Output]) RunAndReturn(run func(ctx context.Context, baggage *Baggage) (EngineOutput[Baggage, Output], error)) *MockEngine_RunBypassBreaker_Call[Baggage, Output] {
	_c.Call.Return(run)
	return _c
}
